name: Conviso IaC Scan
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
workflow_dispatch:

jobs:
 conviso-iac:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.CONVISO_PROJECT_CODE}}
   steps:
   - uses: actions/checkout@v3

   - name: Run IaC Scan
     run: conviso iac run
